FROM opensuse/leap:latest

RUN zypper -n install rlwrap
COPY install/tcl9-x86_64-redhat-linux-rhel8-static-9.0.1 /install-tcl


WORKDIR /app
ENTRYPOINT ["/usr/bin/rlwrap","/install-tcl/bin/tclsh9.0"]

