FROM rleys/kissb-tcl9builder:latest

COPY install/tcl9-x86_64-redhat-linux-rhel8-static-9.0.1 /install-tcl
RUN cd /install-tcl/bin && ln -s tclsh9.0 tclsh

# Critcl
COPY critcl-3.3.1 /critcl-3.3.1
RUN cd /critcl-3.3.1 && /install-tcl/bin/tclsh9.0 ./build.tcl install

WORKDIR /build


