FROM opensuse/leap:latest

RUN zypper -n install rlwrap
COPY install/tcl9-x86_64-redhat-linux-rhel8-shared-9.0.1 /install-tcl

ENV LD_LIBRARY_PATH=/install-tcl/lib

WORKDIR /app
ENTRYPOINT ["/usr/bin/rlwrap","/install-tcl/bin/tclsh9.0"]

