FROM rockylinux/rockylinux:8

COPY install-tcl-x86_64-redhat-linux-rhel8-static-9.0.1 /install-tcl 
COPY install-tk-x86_64-redhat-linux-rhel8-static-9.0.1 /install-tk



#RUN zypper addrepo  https://download.opensuse.org/repositories/X11:XOrg/openSUSE_Tumbleweed/X11:XOrg.repo
#RUN zypper -n refresh  | echo 'a'
#RUN zypper -n install -y libX11 | echo 'a'
RUN dnf install -y libX11

ENV DISPLAY=:0

WORKDIR /build
ENTRYPOINT ["/install-tk/bin/wish9.0"]

