FROM opensuse/leap:latest


ARG tclmajor=9.0
ARG tclminor=9.0.2

## TCL installation
COPY install/tcl9-x86_64-redhat-linux-rhel8-shared-$tclminor            /install-tcl
COPY install/tcl9-x86_64-redhat-linux-rhel8-shared-$tclminor/bin/*      /usr/local/bin
COPY install/tcl9-x86_64-redhat-linux-rhel8-shared-$tclminor/lib/*      /usr/local/lib
COPY install/tcl9-x86_64-redhat-linux-rhel8-shared-$tclminor/share/*    /usr/local/share
COPY install/tcl9-x86_64-redhat-linux-rhel8-shared-$tclminor/include/*  /usr/local/include

## Add Packages
RUN zypper -n install rlwrap

## Add Default user
RUN  useradd -U -m tcl


WORKDIR /app
ENV RLWRAP_HOME=/tmp
ENTRYPOINT ["/usr/bin/rlwrap","tclsh9.0"]

USER tcl
